name: Sync Fork Push

on:
  push:
    branches:
      - dev-bluelovers
  schedule:
## https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
##            ┌───────────── minute (0 - 59)
##            │ ┌───────────── hour (0 - 23)
##            │ │ ┌───────────── day of the month (1 - 31)
##            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
##            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
##            │ │ │ │ │
##            │ │ │ │ │
##            │ │ │ │ │
##            * * * * *
    - cron: '0 0 1 * *'
    - cron: '0 0 15 * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest
    if: 0

    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          token: ${{ secrets.All2024_TOKEN }}
          owner: AUTOMATIC1111
          base: dev-bluelovers
          head: dev
          merge_method: rebase
